version: 2
jobs:
  build:
    docker:
      - image: zxkjack123/python3_jvp:latest
    steps:
      - checkout
      - run: |
         echo "hello world!"
         cd tests
         nosetests3 test_jvp.py
